config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('custofeed.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # DJANGO REST Auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),


    # LOCAL APPS ---------------

    # feedbacks app
    url(r'^feedbacks/', include('custofeed.feedbacks.urls', namespace='feedbacks')),

    # dashboard app
    url(r'^dashboard/', include('custofeed.dashboard.urls', namespace='dashboard')),

    # mails app
    url(r'^mails/', include('custofeed.mails.urls', namespace='mails')),

    # loyalty app
    url(r'^loyalty/', include('custofeed.loyalty.urls', namespace='loyalty')),

    # staff app
    url(r'^staff/', include('custofeed.staff.urls', namespace='staff')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # URLs allowed during development only
    urlpatterns += [
        # This allows the error pages to be debugged during development
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),

        # Django REST Framework
        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

        # DJANGO REST Auth
        url(r'^docs/', include('rest_framework_docs.urls')),
    ]

custofeed/dashboard/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from custofeed.companies import views as companies_views
from custofeed.feedbacks import views as feedbacks_views

from . import views, chart_views

urlpatterns = [
    url(r'^$', views.b2b_dashboard, name='b2b_dashboard'),
    url(r'^activate/$', views.b2b_redirect_activation, name='b2b_redirect_activation'),
    url(r'^register/$', views.b2b_register, name='b2b_register'),
    url(r'^feedback-forms/$', views.b2b_feedback_forms, name='b2b_feedback_forms'),
    url(r'^feedback-forms/creator/$', views.b2b_feedback_form_creator, name='b2b_feedback_form_creator'),
    url(r'^feedback-forms/customizer/$', views.b2b_feedback_form_customizer, name='b2b_feedback_form_customizer'),
    url(r'^feedback-forms/customizer/(?P<pk>[0-9]+)/$', views.b2b_feedback_form_customizer_questions,
        name='b2b_feedback_form_customizer_questions'),
    url(r'^feedbacks/$', views.b2b_feedbacks, name='b2b_feedbacks'),
    url(r'^feedbacks/(?P<pk>[0-9]+)/$', views.b2b_feedback, name='b2b_feedback'),
    url(r'^employees/$', views.b2b_feedback_takers, name='b2b_feedback_takers'),
    url(r'^employees/(?P<pk>[0-9]+)/$', views.b2b_feedback_taker, name='b2b_feedback_taker'),
    url(r'^employees/edit/(?P<pk>[0-9]+)/$', feedbacks_views.b2b_feedback_taker_edit, name='b2b_feedback_taker_edit'),
    url(r'^customers/$', views.b2b_feedbackers, name='b2b_feedbackers'),
    url(r'^customers/(?P<pk>[0-9]+)/$', views.b2b_feedbacker, name='b2b_feedbacker'),
    url(r'^company/$', views.b2b_company, name='b2b_company'),
    url(r'^company/edit/$', companies_views.b2b_company_edit, name='b2b_company_edit'),
    url(r'^stores/$', views.b2b_stores, name='b2b_stores'),
    url(r'^stores/edit/(?P<pk>[0-9]+)/$', companies_views.b2b_store_edit, name='b2b_store_edit'),
    url(r'^feedback-request/$', views.b2b_feedback_request, name='b2b_feedback_request'),
    url(r'^feedbacker-referral/referrer-access/2/$', views.b2b_referral, name='b2b_referral'),
    url(r'^orders/$', views.b2b_orders, name='b2b_orders'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.b2b_order, name='b2b_order'),
    url(r'^subscriptions/$', views.b2b_subscriptions, name='b2b_subscriptions'),
    url(r'^export/$', views.b2b_export_data, name='b2b_export_data'),
    url(r'^promotions/sms/$', views.b2b_promotions_sms, name='b2b_promotions_sms'),
    url(r'^promotions/sms/(?P<pk>[0-9]+)/$', views.b2b_promotions_sms_feedbackers,
        name='b2b_promotions_sms_feedbackers'),
    url(r'^market/$', views.b2b_market, name='b2b_market'),
    url(r'^market/checkout/$', views.b2b_market_checkout, name='b2b_market_checkout'),
    url(r'^loyalty/$', views.b2b_loyalty, name='b2b_loyalty'),
    url(r'^alerts/premium/$', views.b2b_alert_premium, name='b2b_alert_premium'),

    # CRUD
    url(r'^delete/$', views.b2b_delete, name='b2b_delete'),
    url(r'^activate-obj/$', views.b2b_activate, name='b2b_activate'),
    url(r'^edit/(?P<obj_type>[\w\-]+)/(?P<pk>[0-9]+)/$', views.b2b_edit, name='b2b_edit'),

    # Charts
    url(r'^chart-data/(?P<chart>[NSC])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$', chart_views.b2b_charts,
        name='b2b_charts'),
    url(r'^chart-data-employee/(?P<pk>[0-9]+)/(?P<chart>[NSC])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_feedback_taker'),
    url(r'^chart-data-multistore/(?P<chart>[F])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts_multistore, name='b2b_charts_multistore'),
    url(r'^chart-data-sms/(?P<chart>[P])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_sms'),
    url(r'^chart-data-employees/(?P<chart>[F])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_feedback_takers'),
]

custofeed/mails/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^daily-report/$', views.daily_report, name='mails_daily_report'),
]

custofeed/sms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = []

custofeed/staff/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.staff_login, name='staff_login'),
    url(r'^dashboard/$', views.staff_dashboard, name='staff_dashboard'),
    url(r'^users/$', views.staff_users, name='staff_users'),
    url(r'^recharge/$', views.staff_recharge, name='staff_recharge'),
]

custofeed/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

custofeed/market/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.utils.encoding import python_2_unicode_compatible

from model_utils.models import TimeStampedModel
from treebeard.mp_tree import MP_Node

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from custofeed.companies.models import Store
from custofeed.core.behaviours import StatusMixin


@python_2_unicode_compatible
class ProductCategory(MP_Node):
    name = models.CharField(max_length=255, null=False, blank=False, db_index=True)
    description = models.TextField(blank=True)

    node_order_by = ['name']

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        names = [a.name for a in self.get_ancestors()]
        names.append(self.name)
        return " > ".join(names)

    class Meta:
        verbose_name = "Product Category"
        verbose_name_plural = "Product Categories"


@python_2_unicode_compatible
class Product(StatusMixin, TimeStampedModel):
    name = models.CharField(_("name"), max_length=255, null=False, blank=False)
    price = models.FloatField(_("price"), default=0, null=False, blank=False)
    category = models.ForeignKey(ProductCategory, blank=False, null=False)
    quantity = models.PositiveIntegerField(_("quantity"), default=0, null=False, blank=False)
    validity = models.PositiveIntegerField(_("validity"), default=0, null=False, blank=False,
                                           help_text=_('validity in days'))
    description = models.TextField(_("description"), null=True, blank=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class CreditBalance(StatusMixin, TimeStampedModel):
    store = models.OneToOneField(Store, blank=False, null=False)
    balance = models.FloatField(_("balance"), null=False, blank=False, default=0)

    class Meta:
        verbose_name = "Credit Balance"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.store) + ": Rs." + str(self.balance) + '/-'

    def debit(self, val):
        if self.balance - val < 0:
            return False
        else:
            self.balance -= val
            self.save()
            return self.balance

    def credit(self, val):
        self.balance += val
        self.save()
        return self.balance


@python_2_unicode_compatible
class Order(TimeStampedModel):
    credit_balance = models.ForeignKey(CreditBalance, blank=False, null=False)
    ordered_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
    amount = models.FloatField(_("amount"), null=False, blank=False, default=0)
    amount_payed = models.FloatField(_("amount_payed"), null=False, blank=False, default=0)

    def __str__(self):
        return self.credit_balance


@python_2_unicode_compatible
class OrderProduct(TimeStampedModel):
    order = models.ForeignKey(Order, null=False, blank=False)
    product = models.ForeignKey(Product, blank=False, null=False)
    quantity = models.PositiveIntegerField(_("quantity"), default=0, null=False, blank=False)

    def __str__(self):
        string = str(self.product) + " for " + str(self.order)
        return string


@python_2_unicode_compatible
class Recharge(TimeStampedModel):
    amount = models.FloatField(_("amount"), default=0, null=False, blank=False)
    reference_id = models.CharField(_("reference ID"), max_length=20, null=True, blank=True)
    credit_balance = models.ForeignKey(CreditBalance, blank=False, null=False)
    recharge_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.reference_id

    def save(self, *args, **kwargs):
        """
        Update Credit Balance
        """
        credit_balance = self.credit_balance
        credit_balance.balance += self.amount
        credit_balance.save()
        super(Recharge, self).save(*args, **kwargs)

custofeed/companies/forms.py
from django import forms

from custofeed.users.models import UserWorkProfile

from .models import Company, Store, SocialLink


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('name', 'mobile', 'email', 'sector')


class StoreForm(forms.ModelForm):

    class Meta:
        model = Store
        fields = ('name', 'mobile', 'email')


class SocialLinkForm(forms.ModelForm):

    class Meta:
        model = SocialLink
        fields = ('store', 'website', 'link', 'active')

    def __init__(self, user, *args, **kwargs):
        super(SocialLinkForm, self).__init__(*args, **kwargs)
        self.fields['store'].queryset = UserWorkProfile.objects.get(user=user).access_store.all()

custofeed/dashboard/forms.py
from django import forms

from .models import Subscriber


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = ('first_name', 'last_name', 'mobile', 'email', 'active')

custofeed/loyalty/forms.py
from django import forms

from custofeed.users.models import UserWorkProfile
from custofeed.stock.models import StoreProduct

from .models import StoreProductPoints


class StoreProductPointsForm(forms.ModelForm):

    class Meta:
        model = StoreProductPoints
        fields = ('store_product', 'points')

    def __init__(self, user, *args, **kwargs):
        super(StoreProductPointsForm, self).__init__(*args, **kwargs)
        stores = UserWorkProfile.objects.get(user=user).access_store.all()
        self.fields['store_product'].queryset = StoreProduct.objects.filter(store__in=stores)

custofeed/companies/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from custofeed.core.utils import check_simulation
from custofeed.users.models import UserWorkProfile

from .models import Store
from .forms import CompanyForm, StoreForm


@login_required
def b2b_company_edit(request):
    user = check_simulation(request)
    work_profile = get_object_or_404(UserWorkProfile, user=user)
    obj = work_profile.company
    if request.method == "POST":
        form = CompanyForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/company/')
    else:
        form = CompanyForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Company',
        'form': form
    })


@login_required
def b2b_store_edit(request, pk):
    user = check_simulation(request)
    access_stores = UserWorkProfile.objects.get(user=user.pk).access_store.all()
    obj = get_object_or_404(Store, pk=pk)
    if not (obj in access_stores):
        return HttpResponseRedirect('/dashboard/stores/')
    if request.method == "POST":
        form = StoreForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/stores/')
    else:
        form = StoreForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Store',
        'form': form
    })

custofeed/feedbacks/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import FeedbackTaker, Feedback, Answer, QuestionOption
from .forms import FeedbackTakerForm


@login_required
def b2b_feedback_taker_edit(request, pk):
    feedback_taker = get_object_or_404(FeedbackTaker, pk=pk)
    if request.method == "POST":
        form = FeedbackTakerForm(request.POST, instance=feedback_taker)
        if form.is_valid():
            feedback_taker = form.save(commit=False)
            feedback_taker.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/employees/')
    else:
        form = FeedbackTakerForm(instance=feedback_taker)
    return render(request, 'dashboard/form_edit.html', {'form': form})


def feedback_form(request, pk):
    feedback = get_object_or_404(Feedback, pk=pk)
    questions = feedback.feedback_form.get_questions()
    store = feedback.feedback_form.store
    if request.method == "POST":
        if not feedback.completed:
            form = request.POST
            if form.get('ret'):
                for question in questions:
                    if question.type == 1:
                        option = QuestionOption.objects.get(pk=int(form.get(str(question.pk))))
                        Answer.objects.create(feedback=feedback, question=question, option=option)
                    elif question.type == 3:
                        Answer.objects.create(feedback=feedback, question=question,
                                              text=int(form.get(str(question.pk))))
                feedback.type = 2  # DELIVERY TYPE
                feedback.nps = form.get('ret')
                feedback.comment = form.get('comment')
                feedback.timestamp = timezone.now()
                feedback.completed = True
                feedback.save()
    return render(request, 'feedbacks/feedback_form.html', {
        'feedback_id': pk,
        'feedback': feedback,
        'store': store,
        'questions': questions
    })

custofeed/market/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

custofeed/templates/staff/base.html
{% extends "base.html" %}
{% load staticfiles i18n compress %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}
{% block dropmenu %}
<li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
{% endblock dropmenu %}
{% block sidebar %}
  <nav class="sidebar">
    <ul>
      <li>
        <a href="{% url 'staff:staff_dashboard' %}">
          <i class="fa fa-dashboard fa-2x"></i>
          <span class="nav-text">{% trans "Dashboard" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'staff:staff_users' %}">
          <i class="fa fa-users fa-2x"></i>
          <span class="nav-text">{% trans "Users" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'staff:staff_recharge' %}">
          <i class="fa fa-inr fa-2x"></i>
          <span class="nav-text">{% trans "Recharge" %}</span>
        </a>
      </li>
    </ul>
    <ul class="bottom">
      <li>
        <a href="{% url 'account_logout' %}">
          <i class="fa fa-power-off fa-2x"></i>
          <span class="nav-text"> {% trans "Sign out" %} </span>
        </a>
      </li>
    </ul>
  </nav>
  {% endblock sidebar %}

custofeed/templates/staff/dashboard.html
{% extends "staff/base.html" %}
{% load staticfiles i18n compress humanize %}

{% block title %}{% trans "Dashboard" %}{% endblock title %}

{% block content %}
<div class="col-xs-12">
  <div class="text-center">
    <form action="{% url 'staff:staff_dashboard' %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-lg" name="submit" value="send_daily_report">SEND DAILY REPORT
      </button>
    </form>
  </div>
</div>
<div class="tile-grid">
  <div class="col-md-4">
    <a href="{% url 'dashboard:b2b_feedbacks' %}" class="clear-styles">
      <div class="tile ht4 bg-success">
        <div class="tile-head">TOTAL CLIENTS
          <div class="pull-right"><i class="fa fa-user-secret"></i></div>
        </div>
        <div class="pull-down">
          <div class="h1">
            {{nb_companies_total|intcomma}}
          </div>
          <div class="col-xs-4">
            <div class="tile-title">{{nb_companies_today|intcomma}}</div>
            TODAY
          </div>
          <div class="col-xs-4 text-center">
            <div class="tile-title">{{nb_companies_week|intcomma}}</div>
            THIS WEEK
          </div>
          <div class="col-xs-4 text-right">
            <div class="tile-title">{{nb_companies_month|intcomma}}</div>
            THIS MONTH
          </div>
          <div class="col-xs-4 text-left">
            <div class="tile-title">{{nb_companies_yesterday|intcomma}}</div>
            YESTERDAY
          </div>
        </div>
        <div class="bg-icon"><i class="fa fa-user-secret"></i></div>
      </div>
    </a>
  </div>
  <div class="col-md-4">
    <a href="{% url 'dashboard:b2b_feedbacks' %}" class="clear-styles">
      <div class="tile ht4 bg-primary">
        <div class="tile-head">TOTAL FEEDBACKS
          <div class="pull-right"><i class="fa fa-list"></i></div>
        </div>
        <div class="pull-down">
          <div class="h1">
            {{nb_feedbacks_total|intcomma}}
          </div>
          <div class="col-xs-4">
            <div class="tile-title">{{nb_feedbacks_today|intcomma}}</div>
            TODAY
          </div>
          <div class="col-xs-4 text-center">
            <div class="tile-title">{{nb_feedbacks_week|intcomma}}</div>
            THIS WEEK
          </div>
          <div class="col-xs-4 text-right">
            <div class="tile-title">{{nb_feedbacks_month|intcomma}}</div>
            THIS MONTH
          </div>
          <div class="col-xs-4">
            <div class="tile-title">{{nb_feedbacks_yesterday|intcomma}}</div>
            YESTERDAY
          </div>
        </div>
        <div class="bg-icon"><i class="fa fa-list"></i></div>
      </div>
    </a>
  </div>
  <div class="col-md-4">
    <a href="{% url 'dashboard:b2b_feedbacks' %}" class="clear-styles">
      <div class="tile ht4 bg-complete">
        <div class="tile-head">TOTAL CUSTOMERS
          <div class="pull-right"><i class="fa fa-users"></i></div>
        </div>
        <div class="pull-down">
          <div class="h1">
            {{nb_feedbackers_total|intcomma}}
          </div>
          <div class="col-xs-4">
            <div class="tile-title">{{nb_feedbackers_today|intcomma}}</div>
            TODAY
          </div>
          <div class="col-xs-4 text-center">
            <div class="tile-title">{{nb_feedbackers_week|intcomma}}</div>
            THIS WEEK
          </div>
          <div class="col-xs-4 text-right">
            <div class="tile-title">{{nb_feedbackers_month|intcomma}}</div>
            THIS MONTH
          </div>
          <div class="col-xs-4 text-left">
            <div class="tile-title">{{nb_feedbackers_yesterday|intcomma}}</div>
            YESTERDAY
          </div>
        </div>
        <div class="bg-icon"><i class="fa fa-users"></i></div>
      </div>
    </a>
  </div>
</div>
{% endblock content %}

custofeed/templates/staff/recharge.html
{% extends "staff/base.html" %}
{% load staticfiles i18n compress crispy_forms_tags %}

{% block title %}Recharge{% endblock %}

{% block content %}
<div class="col-xs-12">
  <br>
  <div class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addCreditBalance">
    <i class="fa fa-plus"></i> ADD CREDIT BALANCE
  </div>
</div>
<div class="clearfix"></div>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="text-center">
        <div class="h1">STORE CREDIT BALANCES</div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table" id="table">
          <thead>
          <tr>
            <th>STORE</th>
            <th>BALANCE</th>
            <th>RECHARGE</th>
            <th>ACTIVE</th>
            <th>EDIT</th>
          </tr>
          </thead>
          <tbody>
          {% for credit_balance in credit_balances %}
          <tr>
            <td>{{credit_balance.store}}</td>
            <td>{{credit_balance.balance}}</td>
            <td>
              <div class="btn btn-primary btn-xs recharge" data-toggle="modal" data-id="{{credit_balance.pk}}"
                   data-target="#rechargeModal">
                RECHARGE
              </div>
            </td>
            <td>
              {% if credit_balance.active %}
              <form action="{% url 'dashboard:b2b_activate' %}?from={{request.path}}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="type" value="credit_balance">
                <input type="hidden" name="pk" value="{{credit_balance.pk}}">
                <input class="btn btn-danger btn-xs" type="submit" name="submit" value="DEACTIVATE">
              </form>
              {% else %}
              <form action="{% url 'dashboard:b2b_activate' %}?from={{request.path}}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="type" value="credit_balance">
                <input type="hidden" name="pk" value="{{credit_balance.pk}}">
                <input class="btn btn-success btn-xs" type="submit" name="submit" value="ACTIVATE">
              </form>
              {% endif %}
            </td>
            <td>
              <a href="{% url 'dashboard:b2b_edit' 'credit-balance' credit_balance.pk %}?from={{request.path}}" title="Edit"
                 class="btn btn-info btn-xs">
                <i class="fa fa-edit"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="text-center">
        <div class="h1">RECHARGES BY YOU</div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>STORE</th>
            <th>AMOUNT</th>
            <th>TIMESTAMP</th>
          </tr>
          </thead>
          <tbody>
          {% for recharge in recharges %}
          <tr>
            <td>{{recharge.credit_balance.store}}</td>
            <td>{{recharge.amount}}</td>
            <td>{{recharge.created}}</td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block modal %}
<div class="modal fade" id="addCreditBalance" tabindex="-1" role="dialog" aria-labelledby="addCreditBalanceLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
          aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="addCreditBalanceLabel">ADD CREDIT BALANCE</h4>
      </div>
      <div class="modal-body">
        <form method="POST" class="post-form">{% csrf_token %}
          {{ form|crispy }}
          <div class="text-center">
            <button type="submit" name="submit" value="add_credit_balance" class="btn btn-primary">ADD</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="rechargeModal" tabindex="-1" role="dialog" aria-labelledby="rechargeModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
          aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="rechargeModalLabel">RECHARGE</h4>
      </div>
      <div class="modal-body">
        <form method="POST" class="post-form">{% csrf_token %}
          {{ recharge_form|crispy }}
          <div class="text-center">
            <button type="submit" name="submit" value="recharge" class="btn btn-primary">RECHARGE</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock modal %}

{% block javascript %}
<script>
  $('.recharge').click(function() {
    $('#id_credit_balance').val($(this).data('id'));
  });
</script>
{% endblock javascript %}