config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('custofeed.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # DJANGO REST Auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),


    # LOCAL APPS ---------------

    # feedbacks app
    url(r'^feedbacks/', include('custofeed.feedbacks.urls', namespace='feedbacks')),

    # dashboard app
    url(r'^dashboard/', include('custofeed.dashboard.urls', namespace='dashboard')),

    # mails app
    url(r'^mails/', include('custofeed.mails.urls', namespace='mails')),

    # loyalty app
    url(r'^loyalty/', include('custofeed.loyalty.urls', namespace='loyalty')),

    # staff app
    url(r'^staff/', include('custofeed.staff.urls', namespace='staff')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # URLs allowed during development only
    urlpatterns += [
        # This allows the error pages to be debugged during development
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),

        # Django REST Framework
        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

        # DJANGO REST Auth
        url(r'^docs/', include('rest_framework_docs.urls')),
    ]

custofeed/feedbacks/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views, export_csv

urlpatterns = [
    url(r'^form/(?P<pk>[0-9]+)/$', views.feedback_form, name='feedback_form'),

    # Export CSV
    url(r'^export/csv/feedback-form-data/$', export_csv.export_csv_feedback_form_data,
        name='export_csv_feedback_form_data'),
    url(r'^export/csv/export-all-data/admin-access-only/export-as-csv/$', export_csv.export_csv,
        name='export_csv'),
]

custofeed/mails/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^daily-report/$', views.daily_report, name='mails_daily_report'),
]

custofeed/sms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = []

custofeed/staff/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.staff_login, name='staff_login'),
    url(r'^dashboard/$', views.staff_dashboard, name='staff_dashboard'),
    url(r'^users/$', views.staff_users, name='staff_users'),
    url(r'^recharge/$', views.staff_recharge, name='staff_recharge'),
]

custofeed/companies/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from custofeed.core.utils import check_simulation
from custofeed.users.models import UserWorkProfile

from .models import Store
from .forms import CompanyForm, StoreForm


@login_required
def b2b_company_edit(request):
    user = check_simulation(request)
    work_profile = get_object_or_404(UserWorkProfile, user=user)
    obj = work_profile.company
    if request.method == "POST":
        form = CompanyForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/company/')
    else:
        form = CompanyForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Company',
        'form': form
    })


@login_required
def b2b_store_edit(request, pk):
    user = check_simulation(request)
    access_stores = UserWorkProfile.objects.get(user=user.pk).access_store.all()
    obj = get_object_or_404(Store, pk=pk)
    if not (obj in access_stores):
        return HttpResponseRedirect('/dashboard/stores/')
    if request.method == "POST":
        form = StoreForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/stores/')
    else:
        form = StoreForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Store',
        'form': form
    })

custofeed/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import csv
from datetime import timedelta

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.db.models import Sum
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from custofeed.core.formulas import cf_retention_score, cf_satisfaction_score
from custofeed.feedbacks.models import FeedbackForm, Feedback, Question, QuestionCategory, QuestionOption, \
    FeedbackTaker, Feedbacker, Answer, QuestionTemplate, QuestionOptionTemplate
from custofeed.feedbacks.forms import FeedbackerForm, QuestionForm, QuestionOptionForm
from custofeed.core.utils import check_simulation, get_day_range_month
from custofeed.companies.models import Sector, Company, Store, SocialLink
from custofeed.companies.forms import SocialLinkForm
from custofeed.feedbacks.form_factory import question_display
from custofeed.loyalty.forms import StoreProductPointsForm
from custofeed.loyalty.models import StoreProductPoints, FeedbackerPoints, PointsClaimed
from custofeed.market.forms import CreditBalanceForm
from custofeed.market.models import Product, CreditBalance, Order, OrderProduct
from custofeed.market.utils import place_order
from custofeed.sms.forms import SMSTemplateForm
from custofeed.sms.models import SMSBalance, SMSTemplate
from custofeed.sms.templates import sms_send_welcome_bp, sms_send_feedback_request, sms_send_promo
from custofeed.stock.forms import StoreProductForm
from custofeed.stock.models import StoreProduct

from .forms import SubscriberForm
from .models import *


@login_required
def b2b_dashboard(request):
    user = check_simulation(request)
    work_profile = UserWorkProfile.objects.get(user=user)
    access_stores_list = UserWorkProfile.objects.get(user=user.pk).access_store.all()
    access_stores = None
    active_store = None
    if request.method == "POST":
        form = request.POST
        if form.get('store'):
            try:
                access_stores = Store.objects.filter(pk=form.get('store'))
                active_store = access_stores[0].pk
            except Store.DoesNotExist:
                pass
    else:
        access_stores = access_stores_list
    store_ids = []
    for store in access_stores:
        store_ids.append(store.id)
    request.session['access_stores'] = store_ids
    feedback_forms = FeedbackForm.objects.filter(store__in=access_stores)
    feedbacks = Feedback.objects.select_related().filter(feedback_form__in=feedback_forms).order_by('-timestamp')[:20]
    is_multistore = False
    if UserWorkProfile.objects.get(user=user.pk).access_store.count() > 1:
        is_multistore = True

    feedback_forms = FeedbackForm.objects.filter(store__in=access_stores)
    feedback_list = Feedback.objects.filter(feedback_form__in=feedback_forms)

    nb_promoters = 0
    nb_passives = 0
    nb_detractors = 0
    nb_positives = 0
    nb_negatives = 0

    for feedback in feedback_list:
        nps_cat = feedback.get_nps_category()
        if nps_cat == 'promoter':
            nb_promoters += 1
        elif nps_cat == 'passive':
            nb_passives += 1
        else:
            nb_detractors += 1

        if feedback.get_verdict() == 'positive':
            nb_positives += 1
        else:
            nb_negatives += 1

    nb_feedbacks = nb_promoters + nb_passives + nb_detractors

    nb_feedbackers = nb_feedbacks

    timestamp_today = timezone.now()
    feedback_stats_today = Feedback.objects.filter(feedback_form__in=feedback_forms,
                                                   timestamp__date=timestamp_today.date())

    nb_promoters_today = 0
    nb_passives_today = 0
    nb_detractors_today = 0
    nb_positives_today = 0
    nb_negatives_today = 0

    for feedback in feedback_stats_today:
        nps_cat = feedback.get_nps_category()
        if nps_cat == 'promoter':
            nb_promoters_today += 1
        elif nps_cat == 'passive':
            nb_passives_today += 1
        else:
            nb_detractors_today += 1

        if feedback.get_verdict() == 'positive':
            nb_positives_today += 1
        else:
            nb_negatives_today += 1

    nb_feedbacks_today = nb_promoters_today + nb_passives_today + nb_detractors_today

    nb_feedbackers_today = nb_feedbacks_today

    timestamp_yesterday = timezone.now() - timedelta(days=1)
    feedback_stats_yesterday = Feedback.objects.filter(feedback_form__in=feedback_forms,
                                                       timestamp__date=timestamp_yesterday.date())

    nb_promoters_yesterday = 0
    nb_passives_yesterday = 0
    nb_detractors_yesterday = 0
    nb_positives_yesterday = 0
    nb_negatives_yesterday = 0

    for feedback in feedback_stats_yesterday:
        nps_cat = feedback.get_nps_category()
        if nps_cat == 'promoter':
            nb_promoters_yesterday += 1
        elif nps_cat == 'passive':
            nb_passives_yesterday += 1
        else:
            nb_detractors_yesterday += 1

        if feedback.get_verdict() == 'positive':
            nb_positives_yesterday += 1
        else:
            nb_negatives_yesterday += 1

    nb_feedbacks_yesterday = nb_promoters_yesterday + nb_passives_yesterday + nb_detractors_yesterday
    nb_feedbackers_yesterday = nb_feedbacks_yesterday

    try:
        feedback_takers = FeedbackTaker.objects.filter(store__in=access_stores)
    except IndexError:
        return HttpResponseRedirect('/dashboard/employees/')

    feedback_taker_stats = []

    for taker in feedback_takers:
        fdbcks = Feedback.objects.filter(feedback_taker=taker)
        total = 0
        count = 0
        for fd in fdbcks:
            total += fd.get_score()
            count += 1
        feedback_taker_stats.append({
            'feedback_taker': taker,
            'sum': total/count,
            'count': count
        })

    # Upcoming Birthdays and Anniversaries
    feedbackers_dob = Feedbacker.objects.filter(stores__in=access_stores, dob__month=timestamp_today.month).distinct()
    feedbackers_anni = Feedbacker.objects.filter(stores__in=access_stores, anni__month=timestamp_today.month).distinct()

    return render(request, 'dashboard/dashboard.html', {
        'work_profile': work_profile,
        'is_multistore': is_multistore,
        'access_stores': access_stores_list,
        'active_store': active_store,
        'feedbacks': feedbacks,
        'cf_retention_score': cf_retention_score(nb_promoters, nb_passives, nb_detractors),
        'cf_satisfaction_score': cf_satisfaction_score(nb_positives, nb_negatives),
        # Store Feedback stats
        'nb_promoters': nb_promoters,
        'nb_passives': nb_passives,
        'nb_detractors': nb_detractors,
        'nb_feedbacks': nb_feedbacks,
        'nb_positives': nb_positives,
        'nb_negatives': nb_negatives,
        'nb_feedbackers': nb_feedbackers,
        # Store Feedback stats today
        'nb_promoters_today': nb_promoters_today,
        'nb_passives_today': nb_passives_today,
        'nb_detractors_today': nb_detractors_today,
        'nb_feedbacks_today': nb_feedbacks_today,
        'nb_positives_today': nb_positives_today,
        'nb_negatives_today': nb_negatives_today,
        'nb_feedbackers_today': nb_feedbackers_today,
        # Store Feedback stats yesterday
        'nb_promoters_yesterday': nb_promoters_yesterday,
        'nb_passives_yesterday': nb_passives_yesterday,
        'nb_detractors_yesterday': nb_detractors_yesterday,
        'nb_feedbacks_yesterday': nb_feedbacks_yesterday,
        'nb_positives_yesterday': nb_positives_yesterday,
        'nb_negatives_yesterday': nb_negatives_yesterday,
        'nb_feedbackers_yesterday': nb_feedbackers_yesterday,
        'feedback_taker_stats': feedback_taker_stats,
        'feedbackers_dob': feedbackers_dob,
        'feedbackers_anni': feedbackers_anni,
    })


@login_required
def b2b_redirect_activation(request):
    return render(request, 'dashboard/redirect_activation.html', {})


@login_required
def b2b_register(request):
    user = check_simulation(request)
    if not (UserWorkProfile.objects.filter(user=user).exists()
            and UserWorkProfile.objects.get(user=user).is_registered):
        if request.method == "POST":
            form = request.POST
            if form.get('company_name') and form.get('company_sector'):
                try:
                    UserWorkProfile.objects.get(user=user)
                except UserWorkProfile.DoesNotExist:
                    sector = get_object_or_404(Sector, name=form.get('company_sector'))
                    company = Company.objects.create(name=form.get('company_name'), sector=sector)
                    UserWorkProfile.objects.create(user=user, company=company)
                return JsonResponse({
                    'response': 'success'
                })
            elif form.get('store_name') and form.get('store_email'):
                work_profile = UserWorkProfile.objects.get(user=user)
                store = Store.objects.create(company=work_profile.company, name=form.get('store_name'),
                                             email=form.get('store_email'))
                work_profile.access_store.add(store)
                work_profile.save()
                return JsonResponse({
                    'response': 'success'
                })
            elif form.get('first_name') and form.get('last_name'):
                user.first_name = form.get('first_name')
                user.last_name = form.get('last_name')
                user.save()
                return JsonResponse({
                    'response': 'success'
                })
            elif form.get('job_title') and form.get('user_mobile'):
                work_profile = UserWorkProfile.objects.get(user=user)

custofeed/feedbacks/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import FeedbackTaker, Feedback, Answer, QuestionOption
from .forms import FeedbackTakerForm


@login_required
def b2b_feedback_taker_edit(request, pk):
    feedback_taker = get_object_or_404(FeedbackTaker, pk=pk)
    if request.method == "POST":
        form = FeedbackTakerForm(request.POST, instance=feedback_taker)
        if form.is_valid():
            feedback_taker = form.save(commit=False)
            feedback_taker.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/employees/')
    else:
        form = FeedbackTakerForm(instance=feedback_taker)
    return render(request, 'dashboard/form_edit.html', {'form': form})


def feedback_form(request, pk):
    feedback = get_object_or_404(Feedback, pk=pk)
    questions = feedback.feedback_form.get_questions()
    store = feedback.feedback_form.store
    if request.method == "POST":
        if not feedback.completed:
            form = request.POST
            if form.get('ret'):
                for question in questions:
                    if question.type == 1:
                        option = QuestionOption.objects.get(pk=int(form.get(str(question.pk))))
                        Answer.objects.create(feedback=feedback, question=question, option=option)
                    elif question.type == 3:
                        Answer.objects.create(feedback=feedback, question=question,
                                              text=int(form.get(str(question.pk))))
                feedback.type = 2  # DELIVERY TYPE
                feedback.nps = form.get('ret')
                feedback.comment = form.get('comment')
                feedback.timestamp = timezone.now()
                feedback.completed = True
                feedback.save()
    return render(request, 'feedbacks/feedback_form.html', {
        'feedback_id': pk,
        'feedback': feedback,
        'store': store,
        'questions': questions
    })

custofeed/templates/feedbacks/feedback_form.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}CustoFeed{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <!--[if lt IE 8]>
  <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a
    href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  {% block css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  {% compress css %}
  <!-- This file store project specific CSS -->
  <link rel="stylesheet" href="{% static 'css/dashboard/style.min.css' %}">
  {% endcompress %}
  {% endblock %}
</head>

<body>
<div class="flex-container">
  <h1>{{store.company.name}}</h1>
  <h2>{{store.name}}</h2>
  {% if feedback.nps > 0 %}
  <h1>Thank You for your valuable feedback!</h1>
  {% else %}
  <div class="panel panel-default feedback_form">
    <div class="panel-heading">
      <h3 class="text-center">{% trans "Feedback Form" %}</h3>
    </div>
    <div class="panel-body">
      <form method="POST" action="{% url 'feedbacks:feedback_form' feedback_id %}">
        {% csrf_token %}
        <ul>
          {% for question in questions %}
          <li>
            <p class="question_title">{{question.title}}</p>
            <p>
              {% if question.type == 3 %}
              <span class="star-rating">
              <input required type="radio" name="{{question.pk}}" id="{{question.pk}}_1" value="1"><label
                for="{{question.pk}}_1">1</label>
              <input required type="radio" name="{{question.pk}}" id="{{question.pk}}_2" value="2"><label
                for="{{question.pk}}_2">2</label>
              <input required type="radio" name="{{question.pk}}" id="{{question.pk}}_3" value="3"><label
                for="{{question.pk}}_3">3</label>
              <input required type="radio" name="{{question.pk}}" id="{{question.pk}}_4" value="4"><label
                for="{{question.pk}}_4">4</label>
              <input required type="radio" name="{{question.pk}}" id="{{question.pk}}_5" value="5"><label
                for="{{question.pk}}_5">5</label>
            </span>
              {% elif question.type == 1 %}
            <ul class="list-unstyled">
              {% for option in question.get_options %}
              <li><input required type="radio" name="{{question.pk}}" value="{{option.pk}}" id="{{option.pk}}"> <label
                for="{{option.pk}}">{{option.title}}</label>
              </li>
              {% endfor %}
            </ul>
            {% endif %}
            </p>
          </li>
          {% endfor %}
          <li>
            <p class="question_title">How likely are you to recommend us to your friends/colleagues?</p>
            <p>
              <span class="star-rating">
              <input required type="radio" name="ret" id="ret_1" value="1"><label
                for="ret_1">1</label>
              <input required type="radio" name="ret" id="ret_2" value="2"><label
                for="ret_2">2</label>
              <input required type="radio" name="ret" id="ret_3" value="3"><label
                for="ret_3">3</label>
              <input required type="radio" name="ret" id="ret_4" value="4"><label
                for="ret_4">4</label>
              <input required type="radio" name="ret" id="ret_5" value="5"><label
                for="ret_5">5</label>
              <input required type="radio" name="ret" id="ret_6" value="6"><label
                for="ret_6">6</label>
              <input required type="radio" name="ret" id="ret_7" value="7"><label
                for="ret_7">7</label>
              <input required type="radio" name="ret" id="ret_8" value="8"><label
                for="ret_8">8</label>
              <input required type="radio" name="ret" id="ret_9" value="9"><label
                for="ret_9">9</label>
              <input required type="radio" name="ret" id="ret_10" value="10"><label
                for="ret_10">10</label>
            </span>
            </p>
          </li>
          <li>
            <div class="form-group"><label for="comment" class="control-label requiredField">
              Comment<span class="asteriskField">*</span> </label>
              <div class="controls ">
                <textarea class="textarea textArea form-control" rows="3" id="comment" name="comment"
                          placeholder="COMMENT"> </textarea>
              </div>
            </div>
          </li>
        </ul>
        <div class="text-center"><input type="submit" value="SUBMIT" class="btn btn-primary"></div>
      </form>
    </div>
  </div>
  {% endif %}
  <hr>
  <div class="text-center">
    <p>Powered by</p>
    <img src="{% static 'images/dashboard/logo.png' %}" alt="">
  </div>
</div>
<!-- JS FILES  -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous" async></script>
<script src="https://use.fontawesome.com/3412f77613.js" async></script>
</body>

</html>