config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('custofeed.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # DJANGO REST Auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),


    # LOCAL APPS ---------------

    # feedbacks app
    url(r'^feedbacks/', include('custofeed.feedbacks.urls', namespace='feedbacks')),

    # dashboard app
    url(r'^dashboard/', include('custofeed.dashboard.urls', namespace='dashboard')),

    # mails app
    url(r'^mails/', include('custofeed.mails.urls', namespace='mails')),

    # loyalty app
    url(r'^loyalty/', include('custofeed.loyalty.urls', namespace='loyalty')),

    # staff app
    url(r'^staff/', include('custofeed.staff.urls', namespace='staff')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # URLs allowed during development only
    urlpatterns += [
        # This allows the error pages to be debugged during development
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),

        # Django REST Framework
        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

        # DJANGO REST Auth
        url(r'^docs/', include('rest_framework_docs.urls')),
    ]

custofeed/dashboard/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from custofeed.companies import views as companies_views
from custofeed.feedbacks import views as feedbacks_views

from . import views, chart_views

urlpatterns = [
    url(r'^$', views.b2b_dashboard, name='b2b_dashboard'),
    url(r'^activate/$', views.b2b_redirect_activation, name='b2b_redirect_activation'),
    url(r'^register/$', views.b2b_register, name='b2b_register'),
    url(r'^feedback-forms/$', views.b2b_feedback_forms, name='b2b_feedback_forms'),
    url(r'^feedback-forms/creator/$', views.b2b_feedback_form_creator, name='b2b_feedback_form_creator'),
    url(r'^feedback-forms/customizer/$', views.b2b_feedback_form_customizer, name='b2b_feedback_form_customizer'),
    url(r'^feedback-forms/customizer/(?P<pk>[0-9]+)/$', views.b2b_feedback_form_customizer_questions,
        name='b2b_feedback_form_customizer_questions'),
    url(r'^feedbacks/$', views.b2b_feedbacks, name='b2b_feedbacks'),
    url(r'^feedbacks/(?P<pk>[0-9]+)/$', views.b2b_feedback, name='b2b_feedback'),
    url(r'^employees/$', views.b2b_feedback_takers, name='b2b_feedback_takers'),
    url(r'^employees/(?P<pk>[0-9]+)/$', views.b2b_feedback_taker, name='b2b_feedback_taker'),
    url(r'^employees/edit/(?P<pk>[0-9]+)/$', feedbacks_views.b2b_feedback_taker_edit, name='b2b_feedback_taker_edit'),
    url(r'^customers/$', views.b2b_feedbackers, name='b2b_feedbackers'),
    url(r'^customers/(?P<pk>[0-9]+)/$', views.b2b_feedbacker, name='b2b_feedbacker'),
    url(r'^company/$', views.b2b_company, name='b2b_company'),
    url(r'^company/edit/$', companies_views.b2b_company_edit, name='b2b_company_edit'),
    url(r'^stores/$', views.b2b_stores, name='b2b_stores'),
    url(r'^stores/edit/(?P<pk>[0-9]+)/$', companies_views.b2b_store_edit, name='b2b_store_edit'),
    url(r'^feedback-request/$', views.b2b_feedback_request, name='b2b_feedback_request'),
    url(r'^feedbacker-referral/referrer-access/2/$', views.b2b_referral, name='b2b_referral'),
    url(r'^orders/$', views.b2b_orders, name='b2b_orders'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.b2b_order, name='b2b_order'),
    url(r'^subscriptions/$', views.b2b_subscriptions, name='b2b_subscriptions'),
    url(r'^export/$', views.b2b_export_data, name='b2b_export_data'),
    url(r'^promotions/sms/$', views.b2b_promotions_sms, name='b2b_promotions_sms'),
    url(r'^promotions/sms/(?P<pk>[0-9]+)/$', views.b2b_promotions_sms_feedbackers,
        name='b2b_promotions_sms_feedbackers'),
    url(r'^market/$', views.b2b_market, name='b2b_market'),
    url(r'^market/checkout/$', views.b2b_market_checkout, name='b2b_market_checkout'),
    url(r'^loyalty/$', views.b2b_loyalty, name='b2b_loyalty'),
    url(r'^alerts/premium/$', views.b2b_alert_premium, name='b2b_alert_premium'),

    # CRUD
    url(r'^delete/$', views.b2b_delete, name='b2b_delete'),
    url(r'^activate-obj/$', views.b2b_activate, name='b2b_activate'),
    url(r'^edit/(?P<obj_type>[\w\-]+)/(?P<pk>[0-9]+)/$', views.b2b_edit, name='b2b_edit'),

    # Charts
    url(r'^chart-data/(?P<chart>[NSC])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$', chart_views.b2b_charts,
        name='b2b_charts'),
    url(r'^chart-data-employee/(?P<pk>[0-9]+)/(?P<chart>[NSC])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_feedback_taker'),
    url(r'^chart-data-multistore/(?P<chart>[F])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts_multistore, name='b2b_charts_multistore'),
    url(r'^chart-data-sms/(?P<chart>[P])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_sms'),
    url(r'^chart-data-employees/(?P<chart>[F])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_feedback_takers'),
]

custofeed/mails/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^daily-report/$', views.daily_report, name='mails_daily_report'),
]

custofeed/sms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = []

custofeed/staff/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.staff_login, name='staff_login'),
    url(r'^dashboard/$', views.staff_dashboard, name='staff_dashboard'),
    url(r'^users/$', views.staff_users, name='staff_users'),
    url(r'^recharge/$', views.staff_recharge, name='staff_recharge'),
]

custofeed/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

custofeed/companies/forms.py
from django import forms

from custofeed.users.models import UserWorkProfile

from .models import Company, Store, SocialLink


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('name', 'mobile', 'email', 'sector')


class StoreForm(forms.ModelForm):

    class Meta:
        model = Store
        fields = ('name', 'mobile', 'email')


class SocialLinkForm(forms.ModelForm):

    class Meta:
        model = SocialLink
        fields = ('store', 'website', 'link', 'active')

    def __init__(self, user, *args, **kwargs):
        super(SocialLinkForm, self).__init__(*args, **kwargs)
        self.fields['store'].queryset = UserWorkProfile.objects.get(user=user).access_store.all()

custofeed/dashboard/forms.py
from django import forms

from .models import Subscriber


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = ('first_name', 'last_name', 'mobile', 'email', 'active')

custofeed/feedbacks/forms.py
from django import forms

from .models import FeedbackTaker, Feedbacker, Question, QuestionOption


class FeedbackTakerForm(forms.ModelForm):

    class Meta:
        model = FeedbackTaker
        fields = ('store', 'first_name', 'last_name', 'pin', 'mobile')


class FeedbackerForm(forms.ModelForm):

    class Meta:
        model = Feedbacker
        fields = ('first_name', 'last_name', 'mobile', 'email', 'dob', 'anni')


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('title', 'category', 'type')


class QuestionOptionForm(forms.ModelForm):

    class Meta:
        model = QuestionOption
        fields = ('title', 'score')

custofeed/loyalty/forms.py
from django import forms

from custofeed.users.models import UserWorkProfile
from custofeed.stock.models import StoreProduct

from .models import StoreProductPoints


class StoreProductPointsForm(forms.ModelForm):

    class Meta:
        model = StoreProductPoints
        fields = ('store_product', 'points')

    def __init__(self, user, *args, **kwargs):
        super(StoreProductPointsForm, self).__init__(*args, **kwargs)
        stores = UserWorkProfile.objects.get(user=user).access_store.all()
        self.fields['store_product'].queryset = StoreProduct.objects.filter(store__in=stores)

custofeed/market/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import Recharge, CreditBalance


class CreditBalanceForm(forms.ModelForm):

    class Meta:
        model = CreditBalance
        fields = ('store', 'balance', 'active')


class RechargeForm(forms.ModelForm):

    class Meta:
        model = Recharge
        fields = ('amount', 'reference_id', 'credit_balance', 'description')

custofeed/sms/forms.py
from django import forms

from custofeed.users.models import UserWorkProfile

from .models import SMSTemplate


class SMSTemplateForm(forms.ModelForm):

    class Meta:
        model = SMSTemplate
        fields = ('store', 'title', 'message', 'active')

    def __init__(self, user, *args, **kwargs):
        super(SMSTemplateForm, self).__init__(*args, **kwargs)
        self.fields['store'].queryset = UserWorkProfile.objects.get(user=user).access_store.all()

custofeed/companies/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from custofeed.core.utils import check_simulation
from custofeed.users.models import UserWorkProfile

from .models import Store
from .forms import CompanyForm, StoreForm


@login_required
def b2b_company_edit(request):
    user = check_simulation(request)
    work_profile = get_object_or_404(UserWorkProfile, user=user)
    obj = work_profile.company
    if request.method == "POST":
        form = CompanyForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/company/')
    else:
        form = CompanyForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Company',
        'form': form
    })


@login_required
def b2b_store_edit(request, pk):
    user = check_simulation(request)
    access_stores = UserWorkProfile.objects.get(user=user.pk).access_store.all()
    obj = get_object_or_404(Store, pk=pk)
    if not (obj in access_stores):
        return HttpResponseRedirect('/dashboard/stores/')
    if request.method == "POST":
        form = StoreForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/stores/')
    else:
        form = StoreForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Store',
        'form': form
    })

custofeed/feedbacks/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import FeedbackTaker, Feedback, Answer, QuestionOption
from .forms import FeedbackTakerForm


@login_required
def b2b_feedback_taker_edit(request, pk):
    feedback_taker = get_object_or_404(FeedbackTaker, pk=pk)
    if request.method == "POST":
        form = FeedbackTakerForm(request.POST, instance=feedback_taker)
        if form.is_valid():
            feedback_taker = form.save(commit=False)
            feedback_taker.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/employees/')
    else:
        form = FeedbackTakerForm(instance=feedback_taker)
    return render(request, 'dashboard/form_edit.html', {'form': form})


def feedback_form(request, pk):
    feedback = get_object_or_404(Feedback, pk=pk)
    questions = feedback.feedback_form.get_questions()
    store = feedback.feedback_form.store
    if request.method == "POST":
        if not feedback.completed:
            form = request.POST
            if form.get('ret'):
                for question in questions:
                    if question.type == 1:
                        option = QuestionOption.objects.get(pk=int(form.get(str(question.pk))))
                        Answer.objects.create(feedback=feedback, question=question, option=option)
                    elif question.type == 3:
                        Answer.objects.create(feedback=feedback, question=question,
                                              text=int(form.get(str(question.pk))))
                feedback.type = 2  # DELIVERY TYPE
                feedback.nps = form.get('ret')
                feedback.comment = form.get('comment')
                feedback.timestamp = timezone.now()
                feedback.completed = True
                feedback.save()
    return render(request, 'feedbacks/feedback_form.html', {
        'feedback_id': pk,
        'feedback': feedback,
        'store': store,
        'questions': questions
    })

custofeed/loyalty/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import render
from django.http import JsonResponse

from custofeed.users.models import OTPUser
from custofeed.feedbacks.models import Feedbacker

from .models import FeedbackerPoints


def loyalty_login(request):
    verified = False
    if request.method == "POST":
        form = request.POST
        if form.get('authHeader'):
            parsed_data = form.get('authHeader').replace(' ', '').split(',')
            data = {}
            for obj in parsed_data:
                dta = obj.replace('"', '').split('=')
                data[dta[0]] = dta[1]
            try:
                otp_user = OTPUser.objects.get(token=data['oauth_token'])
            except OTPUser.DoesNotExist:
                otp_user = OTPUser.objects.create(token=data['oauth_token'], mobile=form.get('mobile_number'))

            if not otp_user.feedbacker:
                feedbacker = Feedbacker.objects.filter(mobile=otp_user.mobile)
                if feedbacker.exists():
                    otp_user.feedbacker = feedbacker.first()
                    otp_user.save()

            points = FeedbackerPoints.objects.filter(feedbacker=otp_user.feedbacker,
                                                     store__in=otp_user.feedbacker.stores.all())

            body = '<div class="text-center"><h3>Hi ' + otp_user.feedbacker.get_full_name() + '!</h3>'
            if len(points) > 0:
                body += '<p>You have the following points</p><hr/>'
                for point in points:
                    body += (
                        '<h4><small>Store</small> ' + point.store.name + '</h4>' +
                        '<h3>' + str(point.points) + ' <small>points</small></h3></li>'
                    )
            else:
                body += '<h4>No points earned yet!</h4>'
            body += '</div>'

            return JsonResponse({
                'response': body
            })
    return render(request, 'loyalty/login.html', {
        'verified': verified,
    })

custofeed/market/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

custofeed/templates/base.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}CustoFeed{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <!--[if lt IE 8]>
  <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a
    href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  {% block css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  {% compress css %}
  <!-- This file store project specific CSS -->
  <link rel="stylesheet" href="{% static 'css/dashboard/style.min.css' %}">
  {% endcompress %}
  {% endblock %}
</head>

<body>
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false"><span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/dashboard/logo.png' %}"
                                                             alt="CustoFeed Logo"></a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false">
              <i class="fa fa-user"></i>&nbsp;&nbsp;{% if request.session.simulate %}{{request.session.simulate}}
              {% else %}{{user.get_full_name}}{% endif %} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              {% block dropmenu %}
              {% if request.session.simulate %}
              <li><a href="{% url 'users:detail' request.session.simulate %}">{% trans "My Profile" %}</a></li>
              {% else %}
              <li><a href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a></li>
              {% endif %}
              <li><a href="{% url 'dashboard:b2b_company' %}">{% trans "Company" %}</a></li>
              <li><a href="{% url 'dashboard:b2b_subscriptions' %}">{% trans "Subscriptions" %}</a></li>
              {% endblock dropmenu %}
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'account_logout' %}">{% trans "Sign out" %}</a></li>
              {% else %}
              <li><a href="{% url 'account_login' %}">{% trans "Sign In" %}</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
  <label for="sidebarToggle" class="sidebar-toggle"><i class="fa fa-chevron-circle-right"
                                                       aria-hidden="true"></i></label>
  <input type="checkbox" id="sidebarToggle">
  {% block sidebar %}
  <nav class="sidebar">
    <ul>
      <li>
        <a href="{% url 'dashboard:b2b_dashboard' %}">
          <i class="fa fa-dashboard fa-2x"></i>
          <span class="nav-text">{% trans "Dashboard" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_feedback_takers' %}">
          <i class="fa fa-black-tie fa-2x"></i>
          <span class="nav-text">{% trans "Employees" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_feedback_forms' %}">
          <i class="fa fa-list fa-2x"></i>
          <span class="nav-text">{% trans "Feedback Forms" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_feedbacks' %}">
          <i class="fa fa-thumbs-up fa-2x"></i>
          <span class="nav-text">{% trans "Feedbacks" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_feedbackers' %}">
          <i class="fa fa-users fa-2x"></i>
          <span class="nav-text">{% trans "Customers" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_feedback_request' %}">
          <i class="fa fa-star-half-o fa-2x"></i>
          <span class="nav-text">{% trans "Ask Feedback" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_stores' %}">
          <i class="fa fa-building fa-2x"></i>
          <span class="nav-text">{% trans "Stores" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_export_data' %}">
          <i class="fa fa-cloud-download fa-2x"></i>
          <span class="nav-text">{% trans "Export Data" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_market' %}">
          <i class="fa fa-shopping-cart fa-2x"></i>
          <span class="nav-text">{% trans "Market" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_promotions_sms' %}">
          <i class="fa fa-mobile fa-2x"></i>
          <span class="nav-text">{% trans "Promotional SMS" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_loyalty' %}">
          <i class="fa fa-trophy fa-2x"></i>
          <span class="nav-text">{% trans "Loyalty Program" %}</span>
        </a>
      </li>
      <li>
        <a href="{% url 'dashboard:b2b_alert_premium' %}">
          <i class="fa fa-share-alt fa-2x"></i>
          <span class="nav-text">{% trans "Social Media" %}</span>
        </a>
      </li>
    </ul>
    <ul class="bottom">
      <li>
        <a href="{% url 'account_logout' %}">
          <i class="fa fa-power-off fa-2x"></i>
          <span class="nav-text"> {% trans "Sign out" %} </span>
        </a>
      </li>
    </ul>
  </nav>
  {% endblock sidebar %}
</header>
<div class="container">
  {% if request.session.simulate %}
  <div class="snackbar">Z
    Simulating as <b>{{request.session.simulate}}</b>
  </div>
  {% endif %}
  {% if messages %}
  {% for message in messages %}
  <div class="noti {% if message.tags %}noti-{{ message.tags }}{% endif %}">{{ message }}</div>
  {% endfor %}
  {% endif %}
</div>
{% block content %}{% endblock content %} {% block modal %}{% endblock modal %}
<!-- JS FILES  -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous" async></script>
<script src="https://use.fontawesome.com/3412f77613.js" async></script>
<!-- place project specific Javascript in this file -->{% compress js %}
<script src="{% static 'js/dashboard/newstricker.min.js' %}"></script>
<script src="{% static 'js/dashboard/script.min.js' %}"></script>
{% endcompress %}
{% block javascript %}
{% endblock javascript %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80286097-1', 'auto');
  ga('send', 'pageview');

</script>
</body>

</html>