config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('custofeed.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # DJANGO REST Auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),


    # LOCAL APPS ---------------

    # feedbacks app
    url(r'^feedbacks/', include('custofeed.feedbacks.urls', namespace='feedbacks')),

    # dashboard app
    url(r'^dashboard/', include('custofeed.dashboard.urls', namespace='dashboard')),

    # mails app
    url(r'^mails/', include('custofeed.mails.urls', namespace='mails')),

    # loyalty app
    url(r'^loyalty/', include('custofeed.loyalty.urls', namespace='loyalty')),

    # staff app
    url(r'^staff/', include('custofeed.staff.urls', namespace='staff')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # URLs allowed during development only
    urlpatterns += [
        # This allows the error pages to be debugged during development
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),

        # Django REST Framework
        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

        # DJANGO REST Auth
        url(r'^docs/', include('rest_framework_docs.urls')),
    ]

custofeed/dashboard/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from custofeed.companies import views as companies_views
from custofeed.feedbacks import views as feedbacks_views

from . import views, chart_views

urlpatterns = [
    url(r'^$', views.b2b_dashboard, name='b2b_dashboard'),
    url(r'^activate/$', views.b2b_redirect_activation, name='b2b_redirect_activation'),
    url(r'^register/$', views.b2b_register, name='b2b_register'),
    url(r'^feedback-forms/$', views.b2b_feedback_forms, name='b2b_feedback_forms'),
    url(r'^feedback-forms/creator/$', views.b2b_feedback_form_creator, name='b2b_feedback_form_creator'),
    url(r'^feedback-forms/customizer/$', views.b2b_feedback_form_customizer, name='b2b_feedback_form_customizer'),
    url(r'^feedback-forms/customizer/(?P<pk>[0-9]+)/$', views.b2b_feedback_form_customizer_questions,
        name='b2b_feedback_form_customizer_questions'),
    url(r'^feedbacks/$', views.b2b_feedbacks, name='b2b_feedbacks'),
    url(r'^feedbacks/(?P<pk>[0-9]+)/$', views.b2b_feedback, name='b2b_feedback'),
    url(r'^employees/$', views.b2b_feedback_takers, name='b2b_feedback_takers'),
    url(r'^employees/(?P<pk>[0-9]+)/$', views.b2b_feedback_taker, name='b2b_feedback_taker'),
    url(r'^employees/edit/(?P<pk>[0-9]+)/$', feedbacks_views.b2b_feedback_taker_edit, name='b2b_feedback_taker_edit'),
    url(r'^customers/$', views.b2b_feedbackers, name='b2b_feedbackers'),
    url(r'^customers/(?P<pk>[0-9]+)/$', views.b2b_feedbacker, name='b2b_feedbacker'),
    url(r'^company/$', views.b2b_company, name='b2b_company'),
    url(r'^company/edit/$', companies_views.b2b_company_edit, name='b2b_company_edit'),
    url(r'^stores/$', views.b2b_stores, name='b2b_stores'),
    url(r'^stores/edit/(?P<pk>[0-9]+)/$', companies_views.b2b_store_edit, name='b2b_store_edit'),
    url(r'^feedback-request/$', views.b2b_feedback_request, name='b2b_feedback_request'),
    url(r'^feedbacker-referral/referrer-access/2/$', views.b2b_referral, name='b2b_referral'),
    url(r'^orders/$', views.b2b_orders, name='b2b_orders'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.b2b_order, name='b2b_order'),
    url(r'^subscriptions/$', views.b2b_subscriptions, name='b2b_subscriptions'),
    url(r'^export/$', views.b2b_export_data, name='b2b_export_data'),
    url(r'^promotions/sms/$', views.b2b_promotions_sms, name='b2b_promotions_sms'),
    url(r'^promotions/sms/(?P<pk>[0-9]+)/$', views.b2b_promotions_sms_feedbackers,
        name='b2b_promotions_sms_feedbackers'),
    url(r'^market/$', views.b2b_market, name='b2b_market'),
    url(r'^market/checkout/$', views.b2b_market_checkout, name='b2b_market_checkout'),
    url(r'^loyalty/$', views.b2b_loyalty, name='b2b_loyalty'),
    url(r'^alerts/premium/$', views.b2b_alert_premium, name='b2b_alert_premium'),

    # CRUD
    url(r'^delete/$', views.b2b_delete, name='b2b_delete'),
    url(r'^activate-obj/$', views.b2b_activate, name='b2b_activate'),
    url(r'^edit/(?P<obj_type>[\w\-]+)/(?P<pk>[0-9]+)/$', views.b2b_edit, name='b2b_edit'),

    # Charts
    url(r'^chart-data/(?P<chart>[NSC])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$', chart_views.b2b_charts,
        name='b2b_charts'),
    url(r'^chart-data-employee/(?P<pk>[0-9]+)/(?P<chart>[NSC])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_feedback_taker'),
    url(r'^chart-data-multistore/(?P<chart>[F])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts_multistore, name='b2b_charts_multistore'),
    url(r'^chart-data-sms/(?P<chart>[P])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_sms'),
    url(r'^chart-data-employees/(?P<chart>[F])/(?P<scale>[YMDH])/(?P<start>[0-9]+)/(?P<delta>[0-9]+)/$',
        chart_views.b2b_charts, name='b2b_charts_feedback_takers'),
]

custofeed/feedbacks/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views, export_csv

urlpatterns = [
    url(r'^form/(?P<pk>[0-9]+)/$', views.feedback_form, name='feedback_form'),

    # Export CSV
    url(r'^export/csv/feedback-form-data/$', export_csv.export_csv_feedback_form_data,
        name='export_csv_feedback_form_data'),
    url(r'^export/csv/export-all-data/admin-access-only/export-as-csv/$', export_csv.export_csv,
        name='export_csv'),
]

custofeed/mails/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^daily-report/$', views.daily_report, name='mails_daily_report'),
]

custofeed/sms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = []

custofeed/staff/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.staff_login, name='staff_login'),
    url(r'^dashboard/$', views.staff_dashboard, name='staff_dashboard'),
    url(r'^users/$', views.staff_users, name='staff_users'),
    url(r'^recharge/$', views.staff_recharge, name='staff_recharge'),
]

custofeed/companies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils.translation import ugettext_lazy as _
from treebeard.mp_tree import MP_Node
from model_utils.models import TimeStampedModel
from custofeed.core.behaviours import MobileMixin, StatusMixin


@python_2_unicode_compatible
class Sector(MP_Node):
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(blank=True)

    node_order_by = ['name']

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        names = [a.name for a in self.get_ancestors()]
        names.append(self.name)
        return " > ".join(names)


@python_2_unicode_compatible
class Company(MobileMixin, TimeStampedModel):
    name = models.CharField(_("company name"), max_length=255, blank=False, null=False)
    email = models.EmailField(_('email address'), blank=True)
    sector = models.ForeignKey(Sector, blank=False, null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "companies"


@python_2_unicode_compatible
class Store(MobileMixin, TimeStampedModel):
    company = models.ForeignKey(Company, blank=False, null=False)
    name = models.CharField(_("store name"), max_length=255, blank=False, null=False)
    email = models.EmailField(_('email address'), blank=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class SocialLink(StatusMixin, TimeStampedModel):
    """
    Social links for store
    """
    store = models.ForeignKey(Store, blank=False, null=False)
    website = models.CharField(_("website"), max_length=255, blank=False, null=False)
    link = models.CharField(_("link"), max_length=255, blank=False, null=False)

    def __str__(self):
        return self.store.name + ' ' + self.website

custofeed/companies/forms.py
from django import forms

from custofeed.users.models import UserWorkProfile

from .models import Company, Store, SocialLink


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('name', 'mobile', 'email', 'sector')


class StoreForm(forms.ModelForm):

    class Meta:
        model = Store
        fields = ('name', 'mobile', 'email')


class SocialLinkForm(forms.ModelForm):

    class Meta:
        model = SocialLink
        fields = ('store', 'website', 'link', 'active')

    def __init__(self, user, *args, **kwargs):
        super(SocialLinkForm, self).__init__(*args, **kwargs)
        self.fields['store'].queryset = UserWorkProfile.objects.get(user=user).access_store.all()

custofeed/dashboard/forms.py
from django import forms

from .models import Subscriber


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = ('first_name', 'last_name', 'mobile', 'email', 'active')

custofeed/feedbacks/forms.py
from django import forms

from .models import FeedbackTaker, Feedbacker, Question, QuestionOption


class FeedbackTakerForm(forms.ModelForm):

    class Meta:
        model = FeedbackTaker
        fields = ('store', 'first_name', 'last_name', 'pin', 'mobile')


class FeedbackerForm(forms.ModelForm):

    class Meta:
        model = Feedbacker
        fields = ('first_name', 'last_name', 'mobile', 'email', 'dob', 'anni')


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('title', 'category', 'type')


class QuestionOptionForm(forms.ModelForm):

    class Meta:
        model = QuestionOption
        fields = ('title', 'score')

custofeed/companies/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from custofeed.core.utils import check_simulation
from custofeed.users.models import UserWorkProfile

from .models import Store
from .forms import CompanyForm, StoreForm


@login_required
def b2b_company_edit(request):
    user = check_simulation(request)
    work_profile = get_object_or_404(UserWorkProfile, user=user)
    obj = work_profile.company
    if request.method == "POST":
        form = CompanyForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/company/')
    else:
        form = CompanyForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Company',
        'form': form
    })


@login_required
def b2b_store_edit(request, pk):
    user = check_simulation(request)
    access_stores = UserWorkProfile.objects.get(user=user.pk).access_store.all()
    obj = get_object_or_404(Store, pk=pk)
    if not (obj in access_stores):
        return HttpResponseRedirect('/dashboard/stores/')
    if request.method == "POST":
        form = StoreForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/stores/')
    else:
        form = StoreForm(instance=obj)
    return render(request, 'dashboard/form_edit.html', {
        'title': 'Store',
        'form': form
    })

custofeed/feedbacks/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import FeedbackTaker, Feedback, Answer, QuestionOption
from .forms import FeedbackTakerForm


@login_required
def b2b_feedback_taker_edit(request, pk):
    feedback_taker = get_object_or_404(FeedbackTaker, pk=pk)
    if request.method == "POST":
        form = FeedbackTakerForm(request.POST, instance=feedback_taker)
        if form.is_valid():
            feedback_taker = form.save(commit=False)
            feedback_taker.save()
            if request.GET.get('from'):
                return HttpResponseRedirect(request.GET.get('from'))
            else:
                return HttpResponseRedirect('/dashboard/employees/')
    else:
        form = FeedbackTakerForm(instance=feedback_taker)
    return render(request, 'dashboard/form_edit.html', {'form': form})


def feedback_form(request, pk):
    feedback = get_object_or_404(Feedback, pk=pk)
    questions = feedback.feedback_form.get_questions()
    store = feedback.feedback_form.store
    if request.method == "POST":
        if not feedback.completed:
            form = request.POST
            if form.get('ret'):
                for question in questions:
                    if question.type == 1:
                        option = QuestionOption.objects.get(pk=int(form.get(str(question.pk))))
                        Answer.objects.create(feedback=feedback, question=question, option=option)
                    elif question.type == 3:
                        Answer.objects.create(feedback=feedback, question=question,
                                              text=int(form.get(str(question.pk))))
                feedback.type = 2  # DELIVERY TYPE
                feedback.nps = form.get('ret')
                feedback.comment = form.get('comment')
                feedback.timestamp = timezone.now()
                feedback.completed = True
                feedback.save()
    return render(request, 'feedbacks/feedback_form.html', {
        'feedback_id': pk,
        'feedback': feedback,
        'store': store,
        'questions': questions
    })

custofeed/loyalty/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import render
from django.http import JsonResponse

from custofeed.users.models import OTPUser
from custofeed.feedbacks.models import Feedbacker

from .models import FeedbackerPoints


def loyalty_login(request):
    verified = False
    if request.method == "POST":
        form = request.POST
        if form.get('authHeader'):
            parsed_data = form.get('authHeader').replace(' ', '').split(',')
            data = {}
            for obj in parsed_data:
                dta = obj.replace('"', '').split('=')
                data[dta[0]] = dta[1]
            try:
                otp_user = OTPUser.objects.get(token=data['oauth_token'])
            except OTPUser.DoesNotExist:
                otp_user = OTPUser.objects.create(token=data['oauth_token'], mobile=form.get('mobile_number'))

            if not otp_user.feedbacker:
                feedbacker = Feedbacker.objects.filter(mobile=otp_user.mobile)
                if feedbacker.exists():
                    otp_user.feedbacker = feedbacker.first()
                    otp_user.save()

            points = FeedbackerPoints.objects.filter(feedbacker=otp_user.feedbacker,
                                                     store__in=otp_user.feedbacker.stores.all())

            body = '<div class="text-center"><h3>Hi ' + otp_user.feedbacker.get_full_name() + '!</h3>'
            if len(points) > 0:
                body += '<p>You have the following points</p><hr/>'
                for point in points:
                    body += (
                        '<h4><small>Store</small> ' + point.store.name + '</h4>' +
                        '<h3>' + str(point.points) + ' <small>points</small></h3></li>'
                    )
            else:
                body += '<h4>No points earned yet!</h4>'
            body += '</div>'

            return JsonResponse({
                'response': body
            })
    return render(request, 'loyalty/login.html', {
        'verified': verified,
    })

custofeed/market/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

custofeed/templates/dashboard/feedback.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Feedback" %}{% endblock title %}

{% block content %} {% load staticfiles i18n compress %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
        <div class="h3">CREATED ON: {{feedback.timestamp}}</div>
        <div class="h3">FORM: <a href="{% url 'dashboard:b2b_feedback_forms' %}">{{feedback.feedback_form}}</a></div>
        <div class="h3">STORE: {{feedback.feedback_form.store}}</div>
        <div class="h3">CUSTOMER: <a href="{% url 'dashboard:b2b_feedbacker' feedback.feedbacker.pk %}">{{feedback.feedbacker}}</a>
        </div>
        {% if feedback.feedback_taker %}<div class="h3">EMPLOYEE: <a
          href="{% url 'dashboard:b2b_feedback_taker' feedback.feedback_taker.pk %}">{{feedback.feedback_taker}}</a></div>{% endif %}
      <div class="h3">COMMENT:</div>
      <p>{{feedback.comment|linebreaks}}</p>
    </div>
  </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">ANSWERS</div>
      </div>
      <div class="panel-body">
        <ul class="question-list">
          {% for answer in answers %}
          <li>
            <label>{{answer.get_answer_display|safe}}</label>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

custofeed/templates/dashboard/feedback_taker.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Employee" %}{% endblock title %}

{% block content %} {% load staticfiles i18n compress %}
<div class="container">
  <div class="text-center">
    <div class="h1">{{feedback_taker}}</div>
    <div class="h3"><i class="fa fa-home"></i> {{feedback_taker.store}}</div>
    <div class="h3"><i class="fa fa-lock"></i> {{feedback_taker.pin}}</div>
    <div class="h3"><i class="fa fa-phone"></i> {{feedback_taker.mobile}}</div>
    <div class="h3"><i class="fa fa-envelope"></i> {{feedback_taker.email}}</div>
    {% if feedback_taker.address %}
    <div class="h3"><i class="fa fa-home"></i> {{feedback_taker.address|linebreaks}}</div>
    {% endif %}
  </div>
  <div class="tile ht6 no-padding">
    <div class="content" id="chart1Heading">
      <div class="col-xs-12">
        <div class="h3 tile-heading">{{feedback_taker}} Performance</div>
        <button class="chart-toggle btn btn-default" data-chart='S'
                data-url="{% url 'dashboard:b2b_charts_feedback_taker' feedback_taker.pk 'S' 'M' 0 12 %}"
                data-start="0" data-delta="30">YEAR
        </button>
        <button class="chart-toggle btn btn-primary" data-chart='S'
                data-url="{% url 'dashboard:b2b_charts_feedback_taker' feedback_taker.pk 'S' 'D' 0 30 %}"
                data-start="0" data-delta="30">MONTH
        </button>
        <button class="chart-toggle btn btn-default" data-chart='S'
                data-url="{% url 'dashboard:b2b_charts_feedback_taker' feedback_taker.pk 'S' 'D' 0 7 %}"
                data-start="0" data-delta="30">WEEK
        </button>
        <button class="chart-toggle btn btn-default" data-chart='S'
                data-url="{% url 'dashboard:b2b_charts_feedback_taker' feedback_taker.pk 'S' 'H' 0 24 %}"
                data-start="0" data-delta="30">DAY
        </button>
      </div>
    </div>
    <div class="col-xs-12">
      <div id="chart1">
      </div>
    </div>
  </div>
  <hr>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="text-center">
        <div class="h1">Feedbacks Taken by {{feedback_taker}}</div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <th>CUSTOMER</th>
          <th>CF RETENTION SCORE</th>
          <th>CF SATISFACTION SCORE</th>
          <th>COMMENT</th>
          <th>TIMESTAMP</th>
          </thead>
          <tbody>
          {% for feedback in feedbacks %}
          <tr>
            <td><a href="{% url 'dashboard:b2b_feedbacker' feedback.feedbacker.pk %}">{{feedback.feedbacker}}</a></td>
            <td>{{feedback.nps}}</td>
            <td>{{feedback.get_score}}</td>
            <td>{{feedback.comment}}</td>
            <td>{{feedback.timestamp}}</td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
    $(function () {
        plotChart('S', "{% url 'dashboard:b2b_charts_feedback_taker' feedback_taker.pk 'S' 'D' 0 30 %}");
    })
</script>
{% endblock javascript %}

custofeed/templates/dashboard/stores.html
{% extends "base.html" %}

{% load staticfiles i18n compress crispy_forms_tags %}

{% block title %}{% trans "Stores" %}{% endblock title %}

{% block content %}
<div class="col-xs-12">
  <br>
  <button class="btn btn-lg btn-primary" disabled><i class="fa fa-plus"></i> ADD A STORE</button>
  <div class="label label-premium"><i class="fa fa-star"></i> PREMIUM</div>
  <small>Multiple stores feature is only available to Premium users.</small>
</div>
{% for store in stores %}
<div class="col-sm-6 col-lg-4">
  <div class="panel panel-default">
    <div class="panel-heading ">
      <div class="panel-title">{{store.0}}</div>
      <div class="panel-controls">
        <ul>
          <li>
            <a href="{% url 'dashboard:b2b_store_edit' store.0.pk %}" class="btn btn-complete btn-xs">
              <i class="fa fa-pencil"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li><b>MOBILE</b>: {{store.0.mobile}}</li>
        <li><b>EMAIL</b>: {{store.0.email}}</li>
        <li><b>ADDRESS</b>: {{store.0.address}}</li>
        <li><b>GEOTAG</b>: LATITUDE: {{store.0.lat}} | LONGITUDE: {{store.0.lng}}</li>
      </ul>
      <hr>
      <div class="h4 text-center">
        SOCIAL LINKS
      </div>
      {% if store.1|length > 0 %}
      <div class="table-responsive">
        <table class="table">
          <thead>
          <th>WEBSITE</th>
          <th>LINK</th>
          <th>ACTIVE</th>
          <th>CONTROLS</th>
          </thead>
          <tbody>
          {% for link in store.1 %}
          <tr>
            <td>
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-{{link.website|lower}} fa-stack-1x fa-inverse"></i>
              </span>
              {{link.website}}
            </td>
            <td>{{link.link}}</td>
            <td>
              {% if link.active %}
              <form action="{% url 'dashboard:b2b_activate' %}?from={{request.path}}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="type" value="social_link">
                <input type="hidden" name="pk" value="{{link.pk}}">
                <input class="btn btn-danger btn-xs" type="submit" name="submit" value="DEACTIVATE">
              </form>
              {% else %}
              <form action="{% url 'dashboard:b2b_activate' %}?from={{request.path}}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="type" value="social_link">
                <input type="hidden" name="pk" value="{{link.pk}}">
                <input class="btn btn-success btn-xs" type="submit" name="submit" value="ACTIVATE">
              </form>
              {% endif %}
            </td>
            <td>
              <a href="{% url 'dashboard:b2b_edit' 'social-link' link.pk %}?from={{request.path}}" title="Edit"
                 class="btn btn-info btn-xs">
                <i class="fa fa-edit"></i>
              </a>
              <form action="{% url 'dashboard:b2b_delete' %}?from={{request.path}}" method="POST" class="form-hori">
                {% csrf_token %}
                <input type="hidden" name="type" value="social_link">
                <input type="hidden" name="pk" value="{{link.pk}}">
                <button title="Delete" class="btn btn-danger btn-xs" type="submit" name="submit">
                  <i class="fa fa-trash"></i>
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <p class="text-center">No Links yet.</p>
      {% endif %}
      <div class="text-center">
        <button class="btn btn-primary addLink" data-toggle="modal" data-target="#addLinkModal"
                data-id="{{store.0.pk}}">
          <i class="fa fa-plus"></i> ADD LINKS
        </button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

{% block modal %}
<div class="modal fade" id="addLinkModal" tabindex="-1" role="dialog" aria-labelledby="addLinkModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
          aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="addLinkModalLabel">ADD CREDIT BALANCE</h4>
      </div>
      <div class="modal-body">
        <form method="POST" class="post-form">{% csrf_token %}
          {{ form|crispy }}
          <div class="text-center">
            <button type="submit" name="submit" value="add_social_link" class="btn btn-primary">ADD</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock modal %}

{% block javascript %}
<script>
  $('.addLink').click(function() {
    $('#id_store').val($(this).data('id'));
  });


</script>
{% endblock javascript %}